"""
    PROGRAM WHICH IS CALCULATE THE OPERATIONS
    AUTHOR : VRAJ PRAJAPATI
"""
class Unstructuredcode:
    def xyzzy(self, a, b):
        result = a + b
        print(f"Result : {result}")
class calculator:
    def add(self, a, b):
        result = a + b
        print(f"Addition Result : {result}")
        
    def multiply(self, a, b):
        result = a * b
        print(f"Multiplication Result : {result}")

def legacy_function(x,y):
    r = x + y
    print(f"Result : {r}")

class Inflexibleshape:
    def calculate_area(self):
        pass
class Circle(Inflexibleshape):
    def calculate_area(self):
        pass
class square(Inflexibleshape):
    def calculate_area(self):
        pass

if __name__ == "__main__":
    # Unstructured code
    unstructuredcode = Unstructuredcode()
    unstructuredcode.xyzzy(5, 10)
    calc = calculator()
    calc.add(5,10)
    calc.multiply(5,10)
    legacy_function(5,10)
    Circle = Circle()
    square = square()
    